spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webshopv2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: webshopv2
    password: 123456


  liquibase:
     change-log: classpath:db/changelog/db.changelog-master.yaml
     url: jdbc:mysql://localhost:3306/webshopv2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     user: webshopv2
     password: 123456

